### PR TITLE
research Temporal

### PR DESCRIPTION
**Pull request by TomasTomecek**
Part of https://github.com/packit/private/issues/25

I just went through the docs and examples, didn't run anything locally on my laptop.

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]
Let's merge so that the one who takes packit/packit-service#2033 can build upon it.

**Comment by TomasTomecek** [comment]
good point, I missed the docusaurus move /o\

Mato, is this good?

**Review by mfocko — APPROVED** [review]
:+1:

**Comment by mfocko** [comment]
Though I should really think about a way how to retrigger the packit.dev builds :D

**Review by lbarcziova — APPROVED** [review]
thank again!

**Pull request merged**
